### ISSUE TITLE
Community Avatar

### ISSUE THREAD

**Issue by nhcarrigan** [carrigan-community/community#2]
We need some sort of icon or logo to represent our community - if anyone is feeling artistic and would like to create one, we'd love to see it!

Anything we use should be our own work, to avoid licensing concerns or issues.

**Comment by LandonLloyd** [comment]
I kinda like the ones used for the discord server. Either the one right now or past images.

**Comment by nhcarrigan** [comment]
Those are, unfortunately, made with Picrew. Which is pretty, but we need something that we own the license to.

**Comment by SashoStoichkov** [comment]
![Carrigan Community (2)](https://user-images.githubusercontent.com/24972335/113153339-a5f7af80-923f-11eb-9c98-2a45b882b2a3.png)

**Comment by nhcarrigan** [comment]
New avatar in place - closing this issue as resolved for now.

If anyone would like to discuss further, feel free to chime in!
